//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.25 at 03:52:28 PM EET 
//


package com.alinma.rib.accounts.model.system.response;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.alinma.rib.models.system.common.CardsListType;
import com.alinma.rib.models.system.common.RecCtrlOutType;


/**
 * <p>Java class for CardsInqBodyRs_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CardsInqBodyRs_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.alinma.com}SentRecs"/>
 *         &lt;element ref="{http://www.alinma.com}RecCtrlOut" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}CardsList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CardsInqBodyRs_Type", propOrder = {
    "sentRecs",
    "recCtrlOut",
    "cardsList"
})
public class CardsInqBodyRsType {

    @XmlElement(name = "SentRecs", required = true)
    protected BigInteger sentRecs;
    @XmlElement(name = "RecCtrlOut")
    protected RecCtrlOutType recCtrlOut;
    @XmlElement(name = "CardsList")
    protected CardsListType cardsList;

    /**
     * Gets the value of the sentRecs property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSentRecs() {
        return sentRecs;
    }

    /**
     * Sets the value of the sentRecs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSentRecs(BigInteger value) {
        this.sentRecs = value;
    }

    /**
     * Gets the value of the recCtrlOut property.
     * 
     * @return
     *     possible object is
     *     {@link RecCtrlOutType }
     *     
     */
    public RecCtrlOutType getRecCtrlOut() {
        return recCtrlOut;
    }

    /**
     * Sets the value of the recCtrlOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecCtrlOutType }
     *     
     */
    public void setRecCtrlOut(RecCtrlOutType value) {
        this.recCtrlOut = value;
    }

    /**
     * Gets the value of the cardsList property.
     * 
     * @return
     *     possible object is
     *     {@link CardsListType }
     *     
     */
    public CardsListType getCardsList() {
        return cardsList;
    }

    /**
     * Sets the value of the cardsList property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardsListType }
     *     
     */
    public void setCardsList(CardsListType value) {
        this.cardsList = value;
    }

}
