//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.15 at 01:56:50 PM EET 
//


package com.alinma.rib.accounts.model.system.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import com.alinma.rib.accounts.model.AcctRecType;



/**
 * <p>Java class for CustAcctDtlsInqBodyRs_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustAcctDtlsInqBodyRs_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.alinma.com}AcctRec_Type">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.alinma.com}AcctId"/>
 *         &lt;element ref="{http://www.alinma.com}AcctSubType" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}IBAN" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}AcctName"/>
 *         &lt;element ref="{http://www.alinma.com}ShortDesc" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}AcctNickname" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}AcctStatus" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}AcctCur" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}StmtCycleFreq" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}StmtDeliveryOpt" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}StmtDeliveryLoc" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}StmtLangPref" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}MT940Enabled"/>
 *         &lt;element ref="{http://www.alinma.com}BranchId" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}AvailBal" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}LedgerBal" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}CurrBal" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}BlockedAmt" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}ATMCardExist" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}SignId" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}OpenReason" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}AcctPurpose" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}PostingRestrictCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}PrimaryRM" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}PrincipleAmt" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}PlacementDt" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}ProfitRate" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}RelAcctInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}ChkAlternId" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustAcctDtlsInqBodyRs_Type")
public class CustAcctDtlsInqBodyRsType
    extends AcctRecType
{


}
