//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.15 at 01:56:50 PM EET 
//

package com.alinma.rib.accounts.model.system.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.alinma.rib.accounts.model.MsgRqHdrType;
import com.alinma.rib.models.system.common.BaseRequest;

/**
 * <p>
 * Java class for CustAcctDtlsInqRq_Type complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="CustAcctDtlsInqRq_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.alinma.com}MsgRqHdr"/>
 *         &lt;element name="Body" type="{http://www.alinma.com}CustAcctDtlsInqBodyRq_Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "CustAcctDtlsInqRq")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustAcctDtlsInqRq_Type", propOrder = { "msgRqHdr", "body" })
public class CustAcctDtlsInqRqType extends BaseRequest {

	@XmlElement(name = "Body", required = true)
	protected CustAcctDtlsInqBodyRqType body;

	/**
	 * Gets the value of the body property.
	 * 
	 * @return possible object is {@link CustAcctDtlsInqBodyRqType }
	 * 
	 */
	public CustAcctDtlsInqBodyRqType getBody() {
		return body;
	}

	/**
	 * Sets the value of the body property.
	 * 
	 * @param value
	 *           allowed object is {@link CustAcctDtlsInqBodyRqType }
	 * 
	 */
	public void setBody(CustAcctDtlsInqBodyRqType value) {
		this.body = value;
	}

}
