/*
 * Account Transfer Transactions
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.alinma.rib.accounts.model.response;
import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AccountTransferTransactionsResponseAccountTransferTransactionsRs
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-01-05T16:29:04.058Z")
public class AccountTransferTransactionsResponseRs {
  @SerializedName("StatusCode")
  private String statusCode = null;

  @SerializedName("StatusDesc")
  private String statusDesc = null;

  @SerializedName("RecCtrlOut")
  private AccountTransferTransactionsResponseAccountTransferTransactionsRsRecCtrlOut recCtrlOut = null;

  @SerializedName("TransferTransactionList")
  private AccountTransferTransactionsRsTransferTransactionList transferTransactionList = null;

  public AccountTransferTransactionsResponseRs statusCode(String statusCode) {
    this.statusCode = statusCode;
    return this;
  }

   /**
   * Get statusCode
   * @return statusCode
  **/
  @ApiModelProperty(value = "")
  public String getStatusCode() {
    return statusCode;
  }

  public void setStatusCode(String statusCode) {
    this.statusCode = statusCode;
  }

  public AccountTransferTransactionsResponseRs statusDesc(String statusDesc) {
    this.statusDesc = statusDesc;
    return this;
  }

   /**
   * Get statusDesc
   * @return statusDesc
  **/
  @ApiModelProperty(value = "")
  public String getStatusDesc() {
    return statusDesc;
  }

  public void setStatusDesc(String statusDesc) {
    this.statusDesc = statusDesc;
  }

  public AccountTransferTransactionsResponseRs recCtrlOut(AccountTransferTransactionsResponseAccountTransferTransactionsRsRecCtrlOut recCtrlOut) {
    this.recCtrlOut = recCtrlOut;
    return this;
  }

   /**
   * Get recCtrlOut
   * @return recCtrlOut
  **/
  @ApiModelProperty(value = "")
  public AccountTransferTransactionsResponseAccountTransferTransactionsRsRecCtrlOut getRecCtrlOut() {
    return recCtrlOut;
  }

  public void setRecCtrlOut(AccountTransferTransactionsResponseAccountTransferTransactionsRsRecCtrlOut recCtrlOut) {
    this.recCtrlOut = recCtrlOut;
  }

  public AccountTransferTransactionsResponseRs transferTransactionList(AccountTransferTransactionsRsTransferTransactionList transferTransactionList) {
    this.transferTransactionList = transferTransactionList;
    return this;
  }

   /**
   * Get transferTransactionList
   * @return transferTransactionList
  **/
  @ApiModelProperty(value = "")
  public AccountTransferTransactionsRsTransferTransactionList getTransferTransactionList() {
    return transferTransactionList;
  }

  public void setTransferTransactionList(AccountTransferTransactionsRsTransferTransactionList transferTransactionList) {
    this.transferTransactionList = transferTransactionList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountTransferTransactionsResponseRs accountTransferTransactionsResponseAccountTransferTransactionsRs = (AccountTransferTransactionsResponseRs) o;
    return Objects.equals(this.statusCode, accountTransferTransactionsResponseAccountTransferTransactionsRs.statusCode) &&
        Objects.equals(this.statusDesc, accountTransferTransactionsResponseAccountTransferTransactionsRs.statusDesc) &&
        Objects.equals(this.recCtrlOut, accountTransferTransactionsResponseAccountTransferTransactionsRs.recCtrlOut) &&
        Objects.equals(this.transferTransactionList, accountTransferTransactionsResponseAccountTransferTransactionsRs.transferTransactionList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(statusCode, statusDesc, recCtrlOut, transferTransactionList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountTransferTransactionsResponseAccountTransferTransactionsRs {\n");
    
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("    statusDesc: ").append(toIndentedString(statusDesc)).append("\n");
    sb.append("    recCtrlOut: ").append(toIndentedString(recCtrlOut)).append("\n");
    sb.append("    transferTransactionList: ").append(toIndentedString(transferTransactionList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

