//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.15 at 01:56:50 PM EET 
//


package com.alinma.rib.accounts.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AcctType_Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AcctType_Type">
 *   &lt;restriction base="{http://www.alinma.com}C">
 *     &lt;maxLength value="2"/>
 *     &lt;enumeration value="CA"/>
 *     &lt;enumeration value="CC"/>
 *     &lt;enumeration value="DC"/>
 *     &lt;enumeration value="IN"/>
 *     &lt;enumeration value="PF"/>
 *     &lt;enumeration value="DA"/>
 *     &lt;enumeration value="SA"/>
 *     &lt;enumeration value="LA"/>
 *     &lt;enumeration value="SC"/>
 *     &lt;enumeration value="CI"/>
 *     &lt;enumeration value="GI"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AcctType_Type")
@XmlEnum
public enum AcctTypeType {

    CA,
    CC,
    DC,
    IN,
    PF,
    DA,
    SA,
    LA,
    SC,
    CI,
    GI;

    public String value() {
        return name();
    }

    public static AcctTypeType fromValue(String v) {
        return valueOf(v);
    }

}
