//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.15 at 01:56:50 PM EET 
//


package com.alinma.rib.accounts.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CustIdentifier_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustIdentifier_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.alinma.com}CustId_Type">
 *       &lt;choice>
 *         &lt;element ref="{http://www.alinma.com}CIF"/>
 *         &lt;element ref="{http://www.alinma.com}AlinmaId"/>
 *         &lt;element ref="{http://www.alinma.com}POI"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustIdentifier_Type")
public class CustIdentifierType
    extends CustIdType
{


}
