//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.15 at 01:56:50 PM EET 
//


package com.alinma.rib.accounts.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CustId_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustId_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.alinma.com}CIF"/>
 *         &lt;element ref="{http://www.alinma.com}AlinmaId"/>
 *         &lt;element ref="{http://www.alinma.com}CardId"/>
 *         &lt;element ref="{http://www.alinma.com}AcctId"/>
 *         &lt;element ref="{http://www.alinma.com}POI"/>
 *         &lt;element ref="{http://www.alinma.com}SysSbscrptnId"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustId_Type", propOrder = {
    "cif",
    "alinmaId",
    "cardId",
    "acctId",
    "poi",
    "sysSbscrptnId"
})
@XmlSeeAlso({
    CustIdentifierType.class,
    AcctOwnerType.class
})
public class CustIdType {

    @XmlElement(name = "CIF")
    protected String cif;
    @XmlElement(name = "AlinmaId")
    protected String alinmaId;
    @XmlElement(name = "CardId")
    protected CardIdType cardId;
    @XmlElement(name = "AcctId")
    protected AcctIdType acctId;
    @XmlElement(name = "POI")
    protected POIType poi;
    @XmlElement(name = "SysSbscrptnId")
    protected SysSbscrptnIdType sysSbscrptnId;

    /**
     * Gets the value of the cif property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCIF() {
        return cif;
    }

    /**
     * Sets the value of the cif property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCIF(String value) {
        this.cif = value;
    }

    /**
     * Gets the value of the alinmaId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlinmaId() {
        return alinmaId;
    }

    /**
     * Sets the value of the alinmaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlinmaId(String value) {
        this.alinmaId = value;
    }

    /**
     * Gets the value of the cardId property.
     * 
     * @return
     *     possible object is
     *     {@link CardIdType }
     *     
     */
    public CardIdType getCardId() {
        return cardId;
    }

    /**
     * Sets the value of the cardId property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardIdType }
     *     
     */
    public void setCardId(CardIdType value) {
        this.cardId = value;
    }

    /**
     * Gets the value of the acctId property.
     * 
     * @return
     *     possible object is
     *     {@link AcctIdType }
     *     
     */
    public AcctIdType getAcctId() {
        return acctId;
    }

    /**
     * Sets the value of the acctId property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcctIdType }
     *     
     */
    public void setAcctId(AcctIdType value) {
        this.acctId = value;
    }

    /**
     * Gets the value of the poi property.
     * 
     * @return
     *     possible object is
     *     {@link POIType }
     *     
     */
    public POIType getPOI() {
        return poi;
    }

    /**
     * Sets the value of the poi property.
     * 
     * @param value
     *     allowed object is
     *     {@link POIType }
     *     
     */
    public void setPOI(POIType value) {
        this.poi = value;
    }

    /**
     * Gets the value of the sysSbscrptnId property.
     * 
     * @return
     *     possible object is
     *     {@link SysSbscrptnIdType }
     *     
     */
    public SysSbscrptnIdType getSysSbscrptnId() {
        return sysSbscrptnId;
    }

    /**
     * Sets the value of the sysSbscrptnId property.
     * 
     * @param value
     *     allowed object is
     *     {@link SysSbscrptnIdType }
     *     
     */
    public void setSysSbscrptnId(SysSbscrptnIdType value) {
        this.sysSbscrptnId = value;
    }

}
