//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.15 at 01:56:50 PM EET 
//


package com.alinma.rib.accounts.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MsgRqHdr_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MsgRqHdr_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.alinma.com}RqUID"/>
 *         &lt;element ref="{http://www.alinma.com}SCId"/>
 *         &lt;element ref="{http://www.alinma.com}FuncId"/>
 *         &lt;element ref="{http://www.alinma.com}RqMode" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}CustLangPref" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}TerminalId" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}TerminalDesc" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}BankId" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}BranchId" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}NetworkRefId" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}CustId" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}UsrId" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}Sec" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}Override" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}AgentId" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}ClientDt" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}EchoData" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}Version" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MsgRqHdr_Type", propOrder = {
    "rqUID",
    "scId",
    "funcId",
    "rqMode",
    "custLangPref",
    "terminalId",
    "terminalDesc",
    "bankId",
    "branchId",
    "networkRefId",
    "custId",
    "usrId",
    "sec",
    "override",
    "agentId",
    "clientDt",
    "echoData",
    "version"
})
public class MsgRqHdrType {

    @XmlElement(name = "RqUID", required = true)
    protected String rqUID;
    @XmlElement(name = "SCId", required = true)
    protected String scId;
    @XmlElement(name = "FuncId", required = true)
    protected String funcId;
    @XmlElement(name = "RqMode")
    protected Long rqMode;
    @XmlElement(name = "CustLangPref")
    protected String custLangPref;
    @XmlElement(name = "TerminalId")
    protected String terminalId;
    @XmlElement(name = "TerminalDesc")
    protected String terminalDesc;
    @XmlElement(name = "BankId")
    protected String bankId;
    @XmlElement(name = "BranchId")
    protected String branchId;
    @XmlElement(name = "NetworkRefId")
    protected String networkRefId;
    @XmlElement(name = "CustId")
    protected CustIdType custId;
    @XmlElement(name = "UsrId")
    protected String usrId;
    @XmlElement(name = "Sec")
    protected List<SecType> sec;
    @XmlElement(name = "Override")
    protected OverrideType override;
    @XmlElement(name = "AgentId")
    protected String agentId;
    @XmlElement(name = "ClientDt")
    protected String clientDt;
    @XmlElement(name = "EchoData")
    protected String echoData;
    @XmlElement(name = "Version")
    protected String version;

    /**
     * Gets the value of the rqUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRqUID() {
        return rqUID;
    }

    /**
     * Sets the value of the rqUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRqUID(String value) {
        this.rqUID = value;
    }

    /**
     * Gets the value of the scId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSCId() {
        return scId;
    }

    /**
     * Sets the value of the scId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSCId(String value) {
        this.scId = value;
    }

    /**
     * Gets the value of the funcId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFuncId() {
        return funcId;
    }

    /**
     * Sets the value of the funcId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFuncId(String value) {
        this.funcId = value;
    }

    /**
     * Gets the value of the rqMode property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRqMode() {
        return rqMode;
    }

    /**
     * Sets the value of the rqMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRqMode(Long value) {
        this.rqMode = value;
    }

    /**
     * Gets the value of the custLangPref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustLangPref() {
        return custLangPref;
    }

    /**
     * Sets the value of the custLangPref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustLangPref(String value) {
        this.custLangPref = value;
    }

    /**
     * Gets the value of the terminalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerminalId() {
        return terminalId;
    }

    /**
     * Sets the value of the terminalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerminalId(String value) {
        this.terminalId = value;
    }

    /**
     * Gets the value of the terminalDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerminalDesc() {
        return terminalDesc;
    }

    /**
     * Sets the value of the terminalDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerminalDesc(String value) {
        this.terminalDesc = value;
    }

    /**
     * Gets the value of the bankId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankId() {
        return bankId;
    }

    /**
     * Sets the value of the bankId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankId(String value) {
        this.bankId = value;
    }

    /**
     * Gets the value of the branchId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranchId() {
        return branchId;
    }

    /**
     * Sets the value of the branchId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranchId(String value) {
        this.branchId = value;
    }

    /**
     * Gets the value of the networkRefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkRefId() {
        return networkRefId;
    }

    /**
     * Sets the value of the networkRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkRefId(String value) {
        this.networkRefId = value;
    }

    /**
     * Gets the value of the custId property.
     * 
     * @return
     *     possible object is
     *     {@link CustIdType }
     *     
     */
    public CustIdType getCustId() {
        return custId;
    }

    /**
     * Sets the value of the custId property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustIdType }
     *     
     */
    public void setCustId(CustIdType value) {
        this.custId = value;
    }

    /**
     * Gets the value of the usrId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsrId() {
        return usrId;
    }

    /**
     * Sets the value of the usrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsrId(String value) {
        this.usrId = value;
    }

    /**
     * Gets the value of the sec property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sec property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSec().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SecType }
     * 
     * 
     */
    public List<SecType> getSec() {
        if (sec == null) {
            sec = new ArrayList<SecType>();
        }
        return this.sec;
    }

    /**
     * Gets the value of the override property.
     * 
     * @return
     *     possible object is
     *     {@link OverrideType }
     *     
     */
    public OverrideType getOverride() {
        return override;
    }

    /**
     * Sets the value of the override property.
     * 
     * @param value
     *     allowed object is
     *     {@link OverrideType }
     *     
     */
    public void setOverride(OverrideType value) {
        this.override = value;
    }

    /**
     * Gets the value of the agentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgentId() {
        return agentId;
    }

    /**
     * Sets the value of the agentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgentId(String value) {
        this.agentId = value;
    }

    /**
     * Gets the value of the clientDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientDt() {
        return clientDt;
    }

    /**
     * Sets the value of the clientDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientDt(String value) {
        this.clientDt = value;
    }

    /**
     * Gets the value of the echoData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEchoData() {
        return echoData;
    }

    /**
     * Sets the value of the echoData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEchoData(String value) {
        this.echoData = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
