//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.15 at 01:56:50 PM EET 
//


package com.alinma.rib.accounts.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MsgRsHdr_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MsgRsHdr_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.alinma.com}StatusCode"/>
 *         &lt;element ref="{http://www.alinma.com}RqUID" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}SPRefNum" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}MsgRecDt" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}OverrideStatus" minOccurs="0"/>
 *         &lt;element ref="{http://www.alinma.com}EchoData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MsgRsHdr_Type", propOrder = {
    "statusCode",
    "rqUID",
    "spRefNum",
    "msgRecDt",
    "overrideStatus",
    "echoData"
})
public class MsgRsHdrType {

    @XmlElement(name = "StatusCode", required = true)
    protected String statusCode;
    @XmlElement(name = "RqUID")
    protected String rqUID;
    @XmlElement(name = "SPRefNum")
    protected String spRefNum;
    @XmlElement(name = "MsgRecDt")
    protected String msgRecDt;
    @XmlElement(name = "OverrideStatus")
    protected OverrideStatusType overrideStatus;
    @XmlElement(name = "EchoData")
    protected String echoData;

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusCode(String value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the rqUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRqUID() {
        return rqUID;
    }

    /**
     * Sets the value of the rqUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRqUID(String value) {
        this.rqUID = value;
    }

    /**
     * Gets the value of the spRefNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPRefNum() {
        return spRefNum;
    }

    /**
     * Sets the value of the spRefNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPRefNum(String value) {
        this.spRefNum = value;
    }

    /**
     * Gets the value of the msgRecDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgRecDt() {
        return msgRecDt;
    }

    /**
     * Sets the value of the msgRecDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgRecDt(String value) {
        this.msgRecDt = value;
    }

    /**
     * Gets the value of the overrideStatus property.
     * 
     * @return
     *     possible object is
     *     {@link OverrideStatusType }
     *     
     */
    public OverrideStatusType getOverrideStatus() {
        return overrideStatus;
    }

    /**
     * Sets the value of the overrideStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link OverrideStatusType }
     *     
     */
    public void setOverrideStatus(OverrideStatusType value) {
        this.overrideStatus = value;
    }

    /**
     * Gets the value of the echoData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEchoData() {
        return echoData;
    }

    /**
     * Sets the value of the echoData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEchoData(String value) {
        this.echoData = value;
    }

}
