//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.15 at 01:56:50 PM EET 
//


package com.alinma.rib.accounts.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SysSbscrptnType_Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SysSbscrptnType_Type">
 *   &lt;restriction base="{http://www.alinma.com}ClosedEnum">
 *     &lt;enumeration value="CIF"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SysSbscrptnType_Type")
@XmlEnum
public enum SysSbscrptnTypeType {

    CIF;

    public String value() {
        return name();
    }

    public static SysSbscrptnTypeType fromValue(String v) {
        return valueOf(v);
    }

}
